/**
 * AI Database Routes - Simplified Version
 * Routes for saving AI-generated questions to the database
 */

import { Router } from 'express';
import { logger } from '@/config/logger';
import { prisma } from '@/config/database';
import { authenticate } from '@/middleware/auth';
import { QuestionType } from '@prisma/client';

export const aiDatabaseRoutes = Router();

/**
 * Save AI-generated questions to database
 * POST /api/ai-db/save-questions
 */
aiDatabaseRoutes.post('/save-questions', authenticate, async (req, res) => {
  try {
    const { questions, topic } = req.body;
    
    if (!questions || !Array.isArray(questions)) {
      return res.status(400).json({
        success: false,
        error: { code: 'INVALID_INPUT', message: 'Questions array is required' }
      });
    }

    logger.info(`Attempting to save ${questions.length} AI questions to database`);
    
    // Find system user for AI questions
    let systemUser = await prisma.user.findUnique({
      where: { email: 'system@quizmaster.com' }
    });

    if (!systemUser) {
      systemUser = await prisma.user.create({
        data: {
          email: 'system@quizmaster.com',
          username: 'QuizMaster AI',
          firstName: 'QuizMaster',
          lastName: 'AI',
          isVerified: true
        }
      });
    }

    // Find or create AI category
    let category = await prisma.category.findFirst({
      where: { slug: 'ai-generated' }
    });

    if (!category) {
      category = await prisma.category.create({
        data: {
          name: 'AI Generated',
          slug: 'ai-generated',
          description: 'Questions generated by AI',
          isActive: true
        }
      });
    }

    let savedCount = 0;
    const errors: string[] = [];

    // Save each question
    for (const aiQuestion of questions) {
      try {
        if (!aiQuestion.questionText || !aiQuestion.correctAnswer) {
          errors.push('Missing required fields');
          continue;
        }

        await prisma.question.create({
          data: {
            questionText: aiQuestion.questionText,
            questionType: aiQuestion.questionType === 'TRUE_FALSE' ? 'TRUE_FALSE' : 'MULTIPLE_CHOICE',
            options: aiQuestion.options || [],
            correctAnswer: aiQuestion.correctAnswer,
            explanation: aiQuestion.explanation || 'Generated by AI',
            difficultyLevel: aiQuestion.difficulty || 2,
            isActive: true,
            isPublished: true,
            tags: [topic || 'AI Generated'],
            createdById: systemUser.id,
            categories: {
              create: [
                { categoryId: category.id }
              ]
            }
          }
        });
        
        savedCount++;
      } catch (error) {
        logger.error('Failed to save individual AI question', error);
        errors.push('Database save error');
      }
    }

    logger.info(`Successfully saved ${savedCount}/${questions.length} AI questions`);

    res.json({
      success: true,
      data: {
        saved: savedCount,
        total: questions.length,
        errors: errors.length,
        topic: topic || 'AI Generated'
      }
    });

  } catch (error) {
    logger.error('Failed to save AI questions to database', error);
    res.status(500).json({
      success: false,
      error: { code: 'DATABASE_ERROR', message: 'Failed to save questions' }
    });
  }
});

/**
 * Get AI question stats
 * GET /api/ai-db/stats
 */
aiDatabaseRoutes.get('/stats', authenticate, async (req, res) => {
  try {
    const aiQuestions = await prisma.question.count({
      where: {
        isActive: true,
        isPublished: true,
        tags: {
          has: 'AI Generated'
        }
      }
    });

    const totalQuestions = await prisma.question.count({
      where: {
        isActive: true,
        isPublished: true
      }
    });

    res.json({
      success: true,
      data: {
        aiQuestions,
        totalQuestions,
        aiPercentage: totalQuestions > 0 ? Math.round((aiQuestions / totalQuestions) * 100) : 0
      }
    });

  } catch (error) {
    logger.error('Failed to get AI question stats', error);
    res.status(500).json({
      success: false,
      error: { code: 'DATABASE_ERROR', message: 'Failed to get stats' }
    });
  }
});