import { logger } from '@/config/logger';

export interface AIQuestionRequest {
  topic: string;
  difficulty: number;
  count: number;
  questionType?: string;
}

export interface AIQuestion {
  questionText: string;
  questionType: string;
  options: string[];
  correctAnswer: string;
  explanation: string;
  difficulty: number;
}

/**
 * Generate AI questions using Google Generative AI
 */
export async function generateAIQuestions(request: AIQuestionRequest): Promise<AIQuestion[]> {
  const { topic, difficulty, count, questionType = 'MULTIPLE_CHOICE' } = request;
  
  logger.info('🤖 AI Question Generation Request:', {
    topic,
    difficulty,
    count,
    questionType
  });

  // Use Google AI (dynamic import for Docker compatibility)  
  const GOOGLE_API_KEY = process.env.GOOGLE_API_KEY || 'AIzaSyB7O_pCoXdzsMAytdUssXNuK0ApF-3PIXg';
  
  logger.info(`🔑 Using API Key: ${GOOGLE_API_KEY.substring(0, 20)}...`);
  
  // Dynamic import to handle missing dependency in Docker
  let genAI, model;
  try {
    const { GoogleGenerativeAI } = require('@google/generative-ai');
    genAI = new GoogleGenerativeAI(GOOGLE_API_KEY);
    model = genAI.getGenerativeModel({ model: 'gemini-1.5-flash' });
  } catch (requireError) {
    logger.error('❌ Google Generative AI not installed in container. Using fallback.');
    throw new Error('AI_PACKAGE_NOT_INSTALLED');
  }

  const prompt = `Generate ${count} quiz questions about "${topic}" with difficulty level ${difficulty} (1=easy, 2=medium, 3=hard, 4=difficult, 5=expert).

Format each question as JSON with this exact structure:
{
  "questionText": "What is...",
  "questionType": "${questionType}",
  "options": ["option1", "option2", "option3", "option4"],
  "correctAnswer": "option1",
  "explanation": "Brief explanation why this answer is correct...",
  "difficulty": ${difficulty},
  "points": 10,
  "estimatedTime": 30
}

CRITICAL REQUIREMENTS:
- Return only valid JSON array
- The correctAnswer MUST be EXACTLY one of the options from the options array
- Do NOT use explanations or descriptions as correctAnswer
- If the question asks about a concept, the options should be the actual answers (like "const", "auto") and correctAnswer should be one of those exact options
- Create engaging, educational questions about ${topic}
- Vary the position of correct answers (don't always put correct answer first)
- Make questions appropriate for difficulty level ${difficulty}
- Questions should test real knowledge about ${topic}

Example:
{
  "questionText": "Which C++ keyword prevents modification of a variable after initialization?",
  "options": ["const", "auto", "static", "volatile"],
  "correctAnswer": "const",
  "explanation": "The const keyword prevents modification of a variable after its initialization.",
  "difficulty": ${difficulty},
  "points": 10,
  "estimatedTime": 30
}

Return ONLY the JSON array, nothing else.`;

  logger.info('📝 Sending request to Google AI...');
  const result = await model.generateContent(prompt);
  const response = await result.response;
  let text = await response.text();
  
  logger.info('📋 Raw AI Response received, length:', text.length);
  
  // Clean up response
  text = text.replace(/```json\n?|```\n?/g, '').trim();
  
  logger.info('🧹 Cleaned response, parsing JSON...');
  
  let questions: AIQuestion[];
  try {
    questions = JSON.parse(text);
  } catch (parseError) {
    logger.error('❌ Failed to parse AI response as JSON', { text, parseError });
    
    // Try to extract JSON from text if it contains extra text
    const jsonMatch = text.match(/\[(.*)\]/s);
    if (jsonMatch) {
      try {
        questions = JSON.parse(jsonMatch[0]);
      } catch (retryError) {
        throw new Error('Failed to parse AI response as JSON');
      }
    } else {
      throw new Error('AI response does not contain valid JSON array');
    }
  }
  
  if (!Array.isArray(questions)) {
    throw new Error('AI response is not an array');
  }

  if (questions.length === 0) {
    throw new Error('AI generated no questions');
  }

  // Validate questions
  const validQuestions = questions.filter((q: any) => {
    if (!q.questionText || !q.options || !Array.isArray(q.options) || !q.correctAnswer) {
      logger.warn('🚫 Invalid AI question structure:', q);
      return false;
    }
    
    // Ensure correctAnswer is one of the options
    if (!q.options.includes(q.correctAnswer)) {
      logger.warn('🚫 AI question correctAnswer not in options:', {
        correctAnswer: q.correctAnswer,
        options: q.options
      });
      return false;
    }
    
    return true;
  });

  if (validQuestions.length === 0) {
    throw new Error('No valid questions generated by AI');
  }

  logger.info(`✅ AI Generated ${validQuestions.length}/${questions.length} valid questions`);
  
  return validQuestions;
}
